### PR TITLE
burn and craft items

### PR DESCRIPTION
**Pull request by brandonbryant12**

### CODE REVIEW

**Review by rafa-js — COMMENTED** [review]
Looking good other than this: https://github.com/HandCash/handcash-cloud/pull/2899/files#r1520886867

Keeping this open until the situation is resolved.

**Comment by rafa-js** [comment]
@brandonbryant12 This just needs to catch up with Cloud and we're done

**Comment by brandonbryant12** [comment]
> @brandonbryant12 This just needs to catch up with Cloud and we're done

ok this is done

**Review by rafa-js — APPROVED** [review]
Awesome 👏

**Pull request merged**
