### PR TITLE
Fixes getEncrypionKeypair

### PR DESCRIPTION
**Pull request by trgsv**

### CODE REVIEW

**Comment by trgsv** [comment]
Fixing a bug which was reported on our Discord server.

**Comment by rseibane** [comment]
> Fixing a bug which was reported on our Discord server.

So this is the fix? https://github.com/HandCash/handcash-connect-sdk-js/pull/54/files#diff-37992a7ecd040561e572f649add339815d2a1fc49569a0cd4cc13cb11a07c2f8R87

What was exactly the issue?

**Comment by trgsv** [comment]
Yes, it should be `Buffer.toString()` instead of `Buffer.toString('hex')` when generating the keypair. Otherwise the format is wrong.
src/profile/index.ts

**Review by rseibane — APPROVED** [review]
LGTM

**Pull request merged**
